name: Build iroha2-ci image

on:
  workflow_dispatch:
    inputs:
      IROHA2_CI_DOCKERFILE:
        required: true
        default: Dockerfile.build

jobs:
  dockerhub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push iroha2-ci image
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: hyperledger/iroha2-ci:nightly-2025-05-08
          labels: commit=${{ github.sha }}
          file: ${{ github.event.inputs.IROHA2_CI_DOCKERFILE }}
          # This context specification is required
          context: .
